#pragma once

// UserState_Skill_0
#define USER_STATE_SKILL_0_0_0 L"../resource/MapleStory/Skill/Skill1/0_0.bmp"
#define USER_STATE_SKILL_0_0_1 L"../resource/MapleStory/Skill/Skill1/0_1.bmp"
#define USER_STATE_SKILL_0_0_2 L"../resource/MapleStory/Skill/Skill1/0_2.bmp"
#define USER_STATE_SKILL_0_0_3 L"../resource/MapleStory/Skill/Skill1/0_3.bmp"
#define USER_STATE_SKILL_0_0_4 L"../resource/MapleStory/Skill/Skill1/0_4.bmp"
#define USER_STATE_SKILL_0_0_5 L"../resource/MapleStory/Skill/Skill1/0_5.bmp"
#define USER_STATE_SKILL_0_0_6 L"../resource/MapleStory/Skill/Skill1/0_6.bmp"
#define USER_STATE_SKILL_0_1_0 L"../resource/MapleStory/Skill/Skill1/1_0.bmp"
#define USER_STATE_SKILL_0_1_1 L"../resource/MapleStory/Skill/Skill1/1_1.bmp"
#define USER_STATE_SKILL_0_1_2 L"../resource/MapleStory/Skill/Skill1/1_2.bmp"
#define USER_STATE_SKILL_0_1_3 L"../resource/MapleStory/Skill/Skill1/1_3.bmp"
#define USER_STATE_SKILL_0_1_4 L"../resource/MapleStory/Skill/Skill1/1_4.bmp"
#define USER_STATE_SKILL_0_1_5 L"../resource/MapleStory/Skill/Skill1/1_5.bmp"
#define USER_STATE_SKILL_0_1_6 L"../resource/MapleStory/Skill/Skill1/1_6.bmp"
#define USER_STATE_SKILL_0_2_0 L"../resource/MapleStory/Skill/Skill1/2_0.bmp"
#define USER_STATE_SKILL_0_2_1 L"../resource/MapleStory/Skill/Skill1/2_1.bmp"
#define USER_STATE_SKILL_0_2_2 L"../resource/MapleStory/Skill/Skill1/2_2.bmp"
#define USER_STATE_SKILL_0_2_3 L"../resource/MapleStory/Skill/Skill1/2_3.bmp"
#define USER_STATE_SKILL_0_2_4 L"../resource/MapleStory/Skill/Skill1/2_4.bmp"
#define USER_STATE_SKILL_0_2_5 L"../resource/MapleStory/Skill/Skill1/2_5.bmp"
#define USER_STATE_SKILL_0_2_6 L"../resource/MapleStory/Skill/Skill1/2_6.bmp"